{"version":1,"defects":{"Error":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #0":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_it_redirects_to_login_page":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_it_shows_login_page":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #2":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #3":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #1":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_valid_credentials_can_login":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #0":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #1":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #2":4,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #3":4},"times":{"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_it_redirects_to_login_page":0.239,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_it_shows_login_page":0.027,"Error":0.001,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #0":0.044,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #1":0.021,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #2":0.027,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_shows_error with data set #3":0.024,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #0":0.031,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #1":0.022,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #2":0.025,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_invalid_credentials_result_in_error with data set #3":0.021,"Davesweb\\Dashboard\\Tests\\Feature\\Auth\\LoginTest::test_valid_credentials_can_login":0.198}}